### PR TITLE
Remove repo clone option for downloading .mod music

### PR DESCRIPTION
**Pull request by samantharamon**
GB Studio 3.0.3 now errors out when cloning the entire repo as well (I cloned via CLI). Downloading the individual files worked for me.

P.S. Thank you for this repo!

### CODE REVIEW

**Comment by mxashlynn** [comment]
I wonder if this is a change in GB Studio or a change in git/GitHub.  Like, perhaps the line endings are altered when downloading via the CLI when they didn't used to be.  I will check if this also happens when downloading via a graphical client.

**Comment by mxashlynn** [comment]
I tested all the files in `Overworld` and `Spooky` on GB Studio 3.0.3 after cloning both from the command line and from GitHub Desktop.  In all cases they worked as expected with no errors reported.

@samantharamon Can you offer any additional information as to what steps you took to lead to the error you experienced, or what the precise error was?  Thanks for your help!

**Comment by samantharamon** [comment]
Thanks for getting back to me and apologies for the delayed response, @mxashlynn. These are the steps I followed:

1. Ran `git clone https://github.com/DeerTears/GB-Studio-Community-Assets.git` in the Terminal app on a Mac (macOS 12.5.1, M1 chip).
2. Copied .mod files from SFX and Spooky folders and added them to the music folder of an existing GB Studio project.
3. In GB Studio, added a 'Play Music Track' event, selected a copied .mod file, and pressed the Play button. Error received:
error
stackTrace

I tested Steps 1 and 2 with a new project, and got the same error. The same error also appears if I attempt to play the tracks through the GB Studio music editor. I haven't had a chance to test this in GitHub Desktop though. I'll give it a shot over the weekend and will let you know how it goes.

**Comment by mxashlynn** [comment]
Thanks, I will look at this soon!

**Comment by mxashlynn** [comment]
Hmm, I wonder if this is a problem that only shows up on Mac.  I will check on Mac tomorrow.

**Comment by mxashlynn** [comment]
Sorry it took me so long to get back to this issue; I ended up getting a bit sick last week.

Thanks a bunch for providing the repro steps!
I followed them and am still not encountering any errors, however.
I was able to clone via the CLI on Mac (12.4, Intel) using git 2.37 and GB Studio 3.0.3 played the songs without issue both in-editor and in a compiled ROM.

A couple of thought spring to mind, though I suspect you've already considered these:

1. I have a pretty basic git setup on my Mac, including not automatically making any changes to the line endings.  Is it possible your git is set up to automatically substitute Unix-style EOLs for Windows-style?
2. Did you set up GB Studio to use GBT Player rather than hUGEtracker?

**Comment by samantharamon** [comment]
No worries! I hope you're feeling better.

Thanks for trying to repro the issue. I checked my git setup and it doesn't automatically make changes to the line endings. My GB Studio was set to hUGEtracker by default, but I switched it to GBT Player since I couldn't get the .mod files to play on it.

There might be something else on my machine that could be causing the issue. I'm happy to close this PR (sorry, I should've opened an issue first) for now, especially since the issue doesn't appear to be reproducible. It works if I download the files individually, so I can keep using that route. I really appreciate your help troubleshooting this. Thank you!

**Comment by mxashlynn** [comment]
I also really appreciate you following through with all of these details, Samantha!
Thanks for helping to keep the repo useful and up-to-date!  :D
In that case, I will go ahead and mark this closed.

**Pull request closed without merging**
